{{- if and .Values.api.enabled .Values.migrations.enabled }}
{{- $ns := default .Release.Namespace .Values.global.namespace -}}
{{- $fullname := include "pytoya.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-migrations-config
  namespace: {{ $ns }}
  labels:
    {{- include "pytoya.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  config.yaml: |
{{ include "pytoya.configYaml" . | nindent 4 }}
{{- end }}
