{{- if and .Values.api.enabled .Values.migrations.enabled }}
{{- $ns := default .Release.Namespace .Values.global.namespace -}}
{{- $fullname := include "pytoya.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-migrations-secrets
  namespace: {{ $ns }}
  labels:
    {{- include "pytoya.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
type: Opaque
stringData:
{{ include "pytoya.secretsStringData" . | nindent 2 }}
{{- end }}
