{{- if and .Values.api.enabled .Values.api.persistence.enabled }}
{{- $ns := default .Release.Namespace .Values.global.namespace -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pytoya.fullname" . }}-api-uploads
  namespace: {{ $ns }}
  labels:
    {{- include "pytoya.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.api.persistence.size }}
  {{- if .Values.api.persistence.storageClass }}
  storageClassName: {{ .Values.api.persistence.storageClass }}
  {{- end }}
{{- end }}
