{{- if .Values.api.enabled }}
{{- $ns := default .Release.Namespace .Values.global.namespace -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pytoya.fullname" . }}-api
  namespace: {{ $ns }}
  labels:
    {{- include "pytoya.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
