{{- $ns := default .Release.Namespace .Values.global.namespace -}}
{{- $fullname := include "pytoya.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-secrets
  namespace: {{ $ns }}
  labels:
    {{- include "pytoya.labels" . | nindent 4 }}
type: Opaque
stringData:
{{ include "pytoya.secretsStringData" . | nindent 2 }}
