{{- if .Values.postgres.enabled }}
{{- $ns := default .Release.Namespace .Values.global.namespace -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pytoya.fullname" . }}-postgres
  namespace: {{ $ns }}
  labels:
    {{- include "pytoya.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ default "ClusterIP" .Values.postgres.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      {{- if and (eq (default "ClusterIP" .Values.postgres.service.type) "NodePort") .Values.postgres.service.nodePort }}
      nodePort: {{ .Values.postgres.service.nodePort }}
      {{- end }}
  selector:
    {{- include "pytoya.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
